// ─── Shared GMB Categories — Single Source of Truth ─────────────────────────
// Used across: LeadScraperModal, CRMPage, AddLeadModal, EditLeadModal, and any
// other page that needs Google My Business industry / category selection.

export const GMB_CATEGORY_GROUPS = [
  {
    group: 'Healthcare & Wellness',
    items: [
      'Dental Clinic', 'Dentist', 'Orthodontist', 'Dental Lab',
      'Medical Clinic', 'General Physician', 'Doctor', 'Polyclinic',
      'Pharmacy', 'Medical Store', 'Chemist',
      'Physiotherapy Clinic', 'Physiotherapist', 'Rehabilitation Center',
      'Eye Clinic', 'Optician', 'Eye Hospital', 'Ophthalmologist',
      'Dermatologist', 'Skin Clinic', 'Cosmetologist', 'Hair Loss Clinic',
      'Gynecologist', 'Maternity Hospital', 'Women Clinic',
      'Pediatric Clinic', 'Pediatrician', 'Children Hospital',
      'Orthopedic Clinic', 'Orthopedic Surgeon', 'Bone Specialist',
      'Diagnostic Lab', 'Pathology Lab', 'X-Ray Center', 'Scan Center', 'MRI Center',
      'Ayurvedic Clinic', 'Homeopathy Clinic', 'Naturopathy Center', 'Unani Clinic',
      'Nursing Home', 'Hospital', 'Multispecialty Hospital',
      'Dietitian', 'Nutritionist', 'Weight Loss Clinic',
      'Psychiatrist', 'Mental Health Clinic', 'Psychologist',
      'ENT Specialist', 'Cardiologist', 'Neurologist', 'Urologist',
      'Gastroenterologist', 'Oncologist', 'Cancer Hospital',
      'IVF Clinic', 'Fertility Clinic', 'Dialysis Center',
      'Acupuncture Clinic', 'Chiropractic Clinic',
      'Blood Bank', 'Ambulance Service',
      'Veterinarian', 'Veterinary Clinic', 'Animal Hospital',
    ],
  },
  {
    group: 'Food & Beverage',
    items: [
      'Restaurant', 'Multi-Cuisine Restaurant', 'Family Restaurant',
      'Cafe', 'Coffee Shop', 'Tea Shop',
      'Fast Food', 'QSR', 'Snack Bar', 'Food Court',
      'Pizza Shop', 'Burger Joint', 'Sandwich Shop',
      'Chinese Restaurant', 'North Indian Restaurant', 'South Indian Restaurant',
      'Biryani Restaurant', 'Mughlai Restaurant', 'Seafood Restaurant',
      'Continental Restaurant', 'Italian Restaurant', 'Thai Restaurant',
      'Vegan Restaurant', 'Vegetarian Restaurant', 'Jain Restaurant',
      'Bakery', 'Cake Shop', 'Pastry Shop', 'Patisserie',
      'Sweet Shop', 'Mithai Shop', 'Namkeen Shop',
      'Juice Bar', 'Smoothie Bar', 'Cold Press Juice',
      'Ice Cream Parlour', 'Gelato Shop', 'Dessert Shop',
      'Dhaba', 'Cloud Kitchen', 'Tiffin Service',
      'Bar', 'Pub', 'Lounge', 'Nightclub', 'Hookah Lounge',
      'Fine Dining', 'Rooftop Restaurant',
      'Catering Service', 'Wedding Catering',
      'Chaat Shop', 'Street Food Stall',
      'Meat Shop', 'Chicken Shop', 'Fish Market',
    ],
  },
  {
    group: 'Beauty & Personal Care',
    items: [
      'Beauty Salon', 'Beauty Parlour', 'Ladies Salon',
      'Hair Salon', 'Barbershop', 'Gents Salon', 'Unisex Salon',
      'Spa', 'Massage Center', 'Thai Spa', 'Ayurvedic Massage',
      'Nail Studio', 'Nail Art', 'Manicure Pedicure',
      'Bridal Makeup Studio', 'Makeup Artist',
      'Tattoo Studio', 'Body Piercing',
      'Waxing Center', 'Threading Center', 'Hair Removal', 'Laser Hair Removal',
      'Skin Care Clinic', 'Facial Studio', 'Anti-Aging Clinic',
      'Hair Treatment Center', 'Hair Spa', 'Keratin Treatment',
      'Hair Transplant Clinic', 'PRP Therapy',
      'Mehndi Artist', 'Eyelash Studio', 'Permanent Makeup',
    ],
  },
  {
    group: 'Fitness & Sports',
    items: [
      'Gym', 'Fitness Center', 'Bodybuilding Gym', 'CrossFit Gym',
      'Yoga Studio', 'Yoga Center', 'Meditation Center',
      'Dance Classes', 'Dance Studio', 'Zumba Classes',
      'Swimming Pool', 'Aquatics Center', 'Swimming Club',
      'Sports Club', 'Sports Ground', 'Turf Ground', 'Indoor Stadium',
      'Martial Arts', 'Karate Classes', 'Boxing Gym', 'MMA Gym',
      'Cricket Academy', 'Football Academy', 'Basketball Court',
      'Badminton Court', 'Tennis Court', 'Table Tennis',
      'Pilates Studio', 'Functional Fitness', 'HIIT Classes',
      'Rock Climbing', 'Golf Club', 'Cycling Club', 'Skating Rink',
    ],
  },
  {
    group: 'Education & Coaching',
    items: [
      'Coaching Institute', 'Tuition Center', 'Study Center',
      'School', 'Preschool', 'Nursery', 'Playschool', 'Kindergarten',
      'Primary School', 'High School', 'CBSE School', 'ICSE School',
      'College', 'University', 'Engineering College',
      'Computer Training', 'Coding Classes', 'IT Training Institute',
      'English Classes', 'Spoken English', 'IELTS Coaching',
      'Music School', 'Guitar Classes', 'Piano Classes',
      'Art Classes', 'Drawing Classes', 'Painting Classes',
      'Vocational Training', 'Skill Development Center', 'ITI',
      'Driving School',
      'JEE Coaching', 'NEET Coaching', 'UPSC Coaching', 'MBA Coaching',
      'SSC Coaching', 'Bank PO Coaching',
      'Abacus Classes', 'Robotics Classes', 'STEM Classes',
    ],
  },
  {
    group: 'Hotels & Accommodation',
    items: [
      'Hotel', 'Budget Hotel', 'Luxury Hotel', 'Boutique Hotel',
      'Lodge', 'Dharamshala',
      'Guest House', 'Bed and Breakfast',
      'Hostel', 'Backpacker Hostel',
      'Resort', 'Beach Resort', 'Hill Resort', 'Eco Resort',
      'Service Apartment', 'Corporate Apartment',
      'PG', 'Paying Guest', 'Working Women Hostel',
      'Homestay', 'Villa Rental', 'Farmhouse Stay',
      'Camp Site', 'Glamping',
    ],
  },
  {
    group: 'Professional Services',
    items: [
      'Chartered Accountant', 'CA Firm', 'Tax Consultant', 'GST Consultant',
      'Lawyer', 'Advocate', 'Law Firm', 'Criminal Lawyer',
      'Architect', 'Architecture Firm',
      'Interior Designer', 'Interior Decorator',
      'Business Consultant', 'Management Consultant',
      'HR Consultant', 'Recruitment Agency', 'Placement Consultant',
      'Insurance Agent', 'LIC Agent', 'Health Insurance Advisor',
      'Notary Public', 'Document Services',
      'Immigration Consultant', 'Visa Consultant',
      'Patent Agent', 'Trademark Registration',
      'Company Secretary', 'Compliance Services',
      'PR Agency', 'Public Relations',
    ],
  },
  {
    group: 'Real Estate & Property',
    items: [
      'Real Estate Agency', 'Property Dealer', 'Housing Broker',
      'Builder', 'Real Estate Developer', 'Township',
      'Co-working Space', 'Shared Office', 'Business Center',
      'Home Loan Advisor', 'Mortgage Consultant',
      'Property Management', 'Facility Management',
      'Commercial Property', 'Office Space Rental',
      'Warehouse', 'Godown', 'Cold Storage',
      'Land Broker', 'Plot Dealer',
    ],
  },
  {
    group: 'Automotive',
    items: [
      'Car Service Center', 'Car Garage', 'Auto Repair', 'Denting Painting',
      'Two-Wheeler Service', 'Bike Service', 'Scooter Service',
      'Tyre Shop', 'Puncture Repair', 'Wheel Alignment',
      'Car Wash', 'Car Detailing',
      'Auto Parts Store', 'Car Accessories Shop',
      'Car Dealership', 'Used Car Dealer',
      'Two-Wheeler Showroom', 'Bike Dealership',
      'EV Service Center', 'EV Charging Station',
      'GPS Tracker Installation', 'Car Audio',
      'Truck Repair', 'Commercial Vehicle Service',
      'Petrol Pump', 'CNG Station',
    ],
  },
  {
    group: 'IT & Technology',
    items: [
      'Web Design Agency', 'Website Design Company', 'Web Development Company',
      'Digital Marketing Agency', 'Online Marketing Company',
      'Software Development Company', 'IT Company', 'SaaS Company',
      'Mobile App Development', 'App Development Company',
      'SEO Agency', 'Content Marketing Agency',
      'IT Support', 'AMC Services', 'Computer Repair', 'Laptop Repair',
      'CCTV Installation', 'Security System', 'Access Control',
      'Graphic Design Studio', 'Creative Agency', 'Branding Studio',
      'Social Media Agency', 'Performance Marketing',
      'E-commerce Solutions', 'Shopify Developer',
      'Cloud Services', 'Cybersecurity Company', 'Data Recovery',
    ],
  },
  {
    group: 'Retail & Shopping',
    items: [
      'Clothing Store', 'Garment Shop', 'Fashion Store', 'Boutique',
      'Electronics Store', 'Appliance Store',
      'Mobile Shop', 'Phone Repair', 'Mobile Accessories',
      'Jewellery Store', 'Gold Shop', 'Diamond Jewellery', 'Artificial Jewellery',
      'Home Furnishing', 'Furniture Store', 'Modular Furniture',
      'Sports Equipment Store',
      'Book Store', 'Stationery Store', 'Gift Shop',
      'Grocery Store', 'Supermarket', 'Departmental Store', 'Kirana Store',
      'Hardware Store', 'Tools Shop',
      'Toy Store', 'Kids Shop',
      'Optical Store', 'Eyewear Shop',
      'Watch Shop', 'Musical Instruments Shop',
      'Bags & Luggage Store', 'Footwear Store', 'Shoe Shop',
      'Saree Shop', 'Ethnic Wear', 'Fabric Store',
      'Baby Products Store', 'Maternity Store',
      'Organic Store', 'Health Products',
      'Cycle Shop', 'Sports Gear',
      'Home Decor', 'Craft Store',
    ],
  },
  {
    group: 'Events & Entertainment',
    items: [
      'Event Management Company', 'Event Planner',
      'Wedding Planner', 'Wedding Coordinator',
      'Photography Studio', 'Wedding Photographer', 'Photographer',
      'Videography', 'Video Production', 'Cinematography',
      'DJ Services', 'Sound System Rental', 'Light Rental',
      'Printing Press', 'Offset Printing', 'Digital Printing', 'Flex Printing',
      'Advertising Agency', 'Outdoor Advertising', 'Hoarding Company',
      'Party Hall', 'Banquet Hall', 'Marriage Hall', 'Wedding Venue',
      'Tent House', 'Decoration Services',
      'Amusement Park', 'Theme Park', 'Water Park',
      'Gaming Zone', 'Bowling Alley', 'Billiards Club',
      'Comedy Club', 'Theater', 'Auditorium',
    ],
  },
  {
    group: 'Home Services & Repairs',
    items: [
      'Pest Control', 'Termite Control',
      'Home Cleaning Service', 'House Cleaning',
      'Plumber', 'Plumbing Services',
      'Electrician', 'Electrical Services',
      'AC Repair', 'Air Conditioning Service', 'HVAC',
      'Carpenter', 'Furniture Repair',
      'House Painting', 'Waterproofing', 'Renovation',
      'Modular Kitchen', 'Kitchen Renovation',
      'Security Guard Service',
      'Washing Machine Repair', 'Refrigerator Repair', 'Appliance Repair',
      'Packers & Movers', 'Relocation Services',
      'False Ceiling Contractor', 'Interior Work',
      'Solar Panel Installation',
      'Water Purifier Service', 'RO Service',
    ],
  },
  {
    group: 'Travel & Transport',
    items: [
      'Travel Agency', 'Tour Operator', 'Holiday Packages',
      'Taxi', 'Cab Service', 'Car Hire',
      'Car Rental', 'Self-Drive Cars',
      'Bus Service', 'Bus Hire', 'Tourist Bus',
      'Courier Service', 'Courier Company',
      'Logistics', 'Transport Company', 'Cargo',
      'Shipping Company', 'Freight Forwarding',
      'Airport Transfer', 'Airport Cab',
      'Trekking Company', 'Adventure Tours',
      'Honeymoon Package', 'International Tours',
      'Pilgrim Tours', 'Religious Travel',
      'Visa Services', 'Passport Consultant',
    ],
  },
  {
    group: 'Finance & Banking',
    items: [
      'Bank', 'Bank Branch', 'Cooperative Bank',
      'Loan Provider', 'NBFC', 'Microfinance',
      'Mutual Fund Advisor', 'SIP Advisor',
      'Stock Broker', 'Demat Account',
      'Money Transfer', 'Western Union', 'Forex',
      'Insurance Company', 'LIC Office',
      'Investment Advisor', 'Financial Planner',
      'Income Tax Filing', 'Tax Returns', 'CA Office',
      'Gold Loan', 'Jewel Loan', 'Pawn Shop',
      'Business Loan', 'Personal Loan',
    ],
  },
  {
    group: 'Construction & Infrastructure',
    items: [
      'Construction Company', 'Building Contractor', 'Civil Contractor',
      'Steel Supplier', 'TMT Bar', 'Iron Steel',
      'Cement Shop', 'Building Material', 'Sand Aggregate',
      'Paint Shop', 'Wall Paint', 'Exterior Paint',
      'Plywood Shop', 'Timber Shop',
      'Tiles Shop', 'Flooring', 'Marble Granite',
      'Glass Shop', 'Aluminium Fabrication',
      'RCC Contractor', 'Waterproofing Contractor',
      'Property Valuer', 'Surveyor',
    ],
  },
  {
    group: 'Manufacturing & Industrial',
    items: [
      'Manufacturing Company', 'Factory', 'Production Unit',
      'Packaging Company', 'Box Making', 'Carton Box',
      'Plastic Products', 'Rubber Products',
      'Metal Fabrication', 'Welding Shop',
      'Chemical Company', 'Industrial Chemicals',
      'Garment Factory', 'Textile Mill',
      'Food Processing Unit', 'Food Manufacturing',
      'Engineering Works', 'CNC Machining',
      'Pump Manufacturer', 'Industrial Equipment Supplier',
    ],
  },
  {
    group: 'Pets & Animals',
    items: [
      'Pet Shop', 'Aquarium Shop',
      'Veterinary Clinic', 'Animal Hospital',
      'Pet Grooming', 'Dog Grooming',
      'Pet Boarding', 'Dog Kennel',
      'Dog Training', 'Pet Training',
      'Bird Shop', 'Pet Food Shop',
    ],
  },
  {
    group: 'Cleaning & Laundry',
    items: [
      'Laundry Service', 'Dry Cleaning', 'Laundromat',
      'Ironing Service', 'Cloth Ironing',
      'Shoe Repair', 'Cobbler',
      'Carpet Cleaning', 'Sofa Cleaning',
      'Office Cleaning', 'Commercial Cleaning',
    ],
  },
  {
    group: 'Media & Print',
    items: [
      'Printing Press', 'Offset Printing', 'Digital Printing',
      'T-Shirt Printing', 'Customized Gifts',
      'Advertising Agency', 'Branding Agency',
      'Video Editing', 'Content Creation Studio',
      'Recording Studio', 'Podcast Studio',
      'Photography Studio', 'Photo Studio',
      'Photo Editing', 'Photo Frame Shop',
    ],
  },
  {
    group: 'Agriculture & Farming',
    items: [
      'Agriculture Shop', 'Seeds & Fertilizer',
      'Plant Nursery', 'Garden Center',
      'Dairy Farm', 'Milk Dairy', 'Organic Farm',
      'Poultry Farm', 'Fish Farm',
      'Agricultural Equipment', 'Tractor Dealer',
      'Greenhouse', 'Hydroponic Farm',
      'Rice Mill', 'Flour Mill',
    ],
  },
  {
    group: 'Religious & Spiritual',
    items: [
      'Temple', 'Mandir', 'Mosque', 'Church', 'Gurudwara',
      'Astrologer', 'Jyotishi', 'Vastu Consultant',
      'Pandit Services', 'Pooja Samagri Shop',
      'Spiritual Center', 'Meditation Center', 'Ashram',
    ],
  },
  {
    group: 'Childcare & Elderly',
    items: [
      'Daycare Center', 'Creche', 'Baby Care',
      'Kids Activity Center', 'Play Zone',
      'Birthday Party Venue', 'Kids Party Hall',
      'Old Age Home', 'Senior Care Center',
      'Home Nursing', 'Elderly Care',
      'Medical Equipment Rental', 'Wheelchair Rental',
    ],
  },
  {
    group: 'Government & NGO',
    items: [
      'Government Office', 'Municipal Office', 'Post Office',
      'Police Station', 'Fire Station',
      'NGO', 'Charitable Organization', 'Social Services',
      'Embassy', 'Consulate',
    ],
  },
  {
    group: 'Miscellaneous',
    items: [
      'Tailor', 'Tailoring Shop', 'Alteration Shop',
      'Locksmith', 'Key Maker',
      'Mobile Recharge', 'DTH Services',
      'Xerox & Printing', 'Photocopy',
      'Courier & Parcel', 'Parcel Service',
      'Second-Hand Store', 'Used Books',
      'Rental Services', 'Equipment Rental',
      'Florist', 'Flower Shop',
      'Balloon Decoration', 'Gift Wrapping',
      'Misc Services',
    ],
  },
]

// ─── Flat list — derived from all groups above ────────────────────────────────
// Use this for simple <select> dropdowns or FilterDropdown components.
export const GMB_INDUSTRIES = GMB_CATEGORY_GROUPS.flatMap((g) => g.items)
